# Generated by Django 5.1.3 on 2024-11-27 02:55

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityCampus',
            fields=[
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=2)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'University Campuses',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
